var x = 1;
try {
  throw 'aaa';
} catch(err if x = 1) {
  console.log(err);
}
